project:
  type: website
  output-dir: docs

website:
  title: "UCSB - Keio Exchange Program"
  favicon: "Images/Logos_Icons/cherry.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:participants
      - sidebar:info
      - href: https://bit.ly/ucsb-gl-24
        text: Apply Now!
        
  sidebar:
      - id: participants
        title: "Participants"
        style: "docked"
        contents:
          - Pages/2023/participants.qmd
      
      - id: info
        title: "Program Info"
        style: "docked"
        contents:
          - Pages/2023/info.qmd

format:
  html:
    theme: [lumen, custom.scss]
    css: styles.css
    toc: true
