project:
  type: website
  output-dir: docs

website:
  title: "UCSB - Keio Exchange Program"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:participants
      - sidebar:info
        
  sidebar:
      - id: participants
        title: "Participants"
        style: "docked"
        contents:
          - Pages/2023/participants.qmd
      
      - id: info
        title: "Program Info"
        style: "docked"
        contents:
          - Pages/2023/info.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
